fixes pipeline

diff --git a/.github/workflows/flutter_emulator_tests.yml b/.github/workflows/flutter_emulator_tests.yml
--- a/.github/workflows/flutter_emulator_tests.yml
+++ b/.github/workflows/flutter_emulator_tests.yml
@@ -43,7 +43,7 @@ jobs:
           appium driver install uiautomator2
           appium driver install --source npm appium-flutter-integration-driver 
 
-      # Step 5: Install Dependencies
+      # Step 5: Install Flutter Dependencies
       - name: Install Flutter Dependencies
         run: |
           flutter pub get
@@ -67,25 +67,29 @@ jobs:
             adb wait-for-device
             adb shell input keyevent 82 &  
 
-      # Step 8: Build & run the App
-      - name: Build & run Flutter App
+      # Step 8: Build the Flutter App
+      - name: Build Flutter App
         run: |
-          flutter run lib/main.dart --dart-define=CORBADO_PROJECT_ID=pro-8751299119685489253 -d emulator-5554 --no-resident
-          sleep 10
-          adb shell am force-stop com.corbado.passkeys.pub
+          flutter build apk --debug
 
-      # Step 9: Start Appium Server
+      # Step 9: Install and Launch the App
+      - name: Install and Launch App
+        run: |
+          adb install -r build/app/outputs/flutter-apk/app-debug.apk
+          adb shell am start -n "com.corbado.passkeys.pub/com.corbado.passkeys.pub.MainActivity"
+
+      # Step 10: Start Appium Server
       - name: Start Appium Server
         run: |
           nohup appium > appium.log 2>&1 &
           sleep 10
 
-      # Step 10: Run Tests
+      # Step 11: Run Tests
       - name: Run Appium Tests
         run: |
           cd tests
           npm i
-          node main.js ios
+          node main.js android
 
   build-test-ios:
     name: Build and Test Flutter App on iOS
@@ -120,7 +124,7 @@ jobs:
           appium driver install uiautomator2
           appium driver install --source npm appium-flutter-integration-driver 
 
-      # Step 5: Install Dependencies
+      # Step 5: Install Flutter Dependencies
       - name: Install Flutter Dependencies
         run: flutter pub get
 
@@ -133,30 +137,38 @@ jobs:
       # Step 7: Launch the iOS Simulator
       - name: Launch iOS Simulator
         run: |
-          xcrun simctl list devices
+          xcrun simctl shutdown all
           xcrun simctl boot "iPhone 16 Pro"
+          while ! xcrun simctl bootstatus | grep -q "Booted"; do
+            echo "Waiting for simulator to boot..."
+            sleep 5
+          done
 
-      # Step 8: Run the app
-      - name: Run the App
+      # Step 8: Build the Flutter App
+      - name: Build Flutter App
         run: |
-          flutter run lib/main.dart --dart-define=CORBADO_PROJECT_ID=pro-8751299119685489253 -d "iPhone 16 Pro" --no-resident
-          sleep 10
-          xcrun simctl terminate booted com.corbado.passkeys.pub
+          flutter build ios --no-codesign
 
-      # Step 9: Start Appium Server
+      # Step 9: Install and Launch the App
+      - name: Install and Launch App
+        run: |
+          xcrun simctl install booted build/ios/iphonesimulator/Runner.app
+          xcrun simctl launch booted com.corbado.passkeys.pub
+
+      # Step 10: Start Appium Server
       - name: Start Appium Server
         run: |
           nohup appium > appium.log 2>&1 & 
           sleep 10
 
-      # Step 10: Run Tests
+      # Step 11: Run Tests
       - name: Run Appium Tests
         run: |
           cd tests
           npm i
           node main.js ios
 
-      # Step 11: Print Appium Logs (if tests fail)
+      # Step 12: Print Appium Logs (if tests fail)
       - name: Print Appium Logs
         if: failure()
         run: |
